---
    - name: Update Cache
      apt:  update_cache=yes

    - name: Upgrade the System
      apt:  upgrade=dist

    - name: install Apache
      apt: name=apache2 state=present

    - name: install mysql
      apt: name={{item}} state=present
      with_items:
          -  mysql-server
          -  libapache2-mod-auth-mysql
          -  php5-mysql

    - name: install php5
      apt:  name={{item}}  state=present
      with_items:
          - php5
          - libapache2-mod-php5
          - php5-mcrypt

    - name: install PHP module for Apache
      apt: name=libapache2-mod-php5 state=present

    - name: Copy PHP script
      copy: src=index.php dest=/var/www/html/index.php mode=0664

    - name: 3. restart Apache
      service: name=apache2 state=restarted enabled=yes

